select CH.CASE_NUMBER,CH.PRIMARY_TYPE, COM.COMMUNITY_AREA_NUMBER
from CHICAGO_CRIME_DATA as CH
INNER JOIN CENSUS_DATA as COM on CH.COMMUNITY_AREA_NUMBER = COM.COMMUNITY_AREA_NUMBER;


select CH.CASE_NUMBER, CH.PRIMARY_TYPE, COM.COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME_DATA as CH
RIGHT OUTER JOIN CENSUS_DATA as COM on CH.COMMUNITY_AREA_NUMBER = COM.COMMUNITY_AREA_NUMBER 
WHERE CH.LOCATION_DESCRIPTION LIKE '%SCHOOL%';

select  COM.COMMUNITY_AREA_NUMBER, CH.CASE_NUMBER
from CHICAGO_CRIME_DATA as CH
FULL OUTER JOIN CENSUS_DATA as COM on CH.COMMUNITY_AREA_NUMBER = COM.COMMUNITY_AREA_NUMBER
WHERE COM.COMMUNITY_AREA_NAME = 'Oakland' OR COM.COMMUNITY_AREA_NAME = 'Armour Square' OR COM.COMMUNITY_AREA_NAME = 'Edgewater' OR COM.COMMUNITY_AREA_NAME = 'CHICAGO'; 



